<h2>API Logs</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>S.No.</th>
			<th>Date Time</th>
			<th>Method</th>
			<th>Url</th>
			<th>Controller/Index</th>
			<th>Data Param</th>
			<th>Status Code</th>
			<th>Response</th>
			<th>Version</th>
			<th>IP</th>
		</tr>
	</thead>
<?php foreach ($this->logs as $key => $value):?>
<tr>
		<td><?php echo ++$key;?></td>
    <?php $data = explode(' ### ', $value);?>
    <?php foreach ($data as $index => $val):?>
        <td><?php echo $val?></td>
    <?php endforeach;?>
</tr>
<?php endforeach;?>
</table>